/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "components/**/*.{vue,js,ts}",
        "modules/**/*.{vue,js,ts}",
        "layouts/**/*.vue",
        "pages/**/*.vue",
        "composables/**/*.{js,ts}",
        "plugins/**/*.{js,ts}",
        "App.{js,ts,vue}",
        "app.{js,ts,vue}",
        "Error.{js,ts,vue}",
        "error.{js,ts,vue}",
    ],
    theme: {
        extend: {
            fontFamily: {
                body: ["Roboto", "sans"],
                logo: ["Dangrek", "sans"],
                title: ["DM Sans", "sans"],
            },
            fontSize: {
                "2xs": ".65rem",
                "3xs": ".5rem",
                "4xs": ".4rem",
            },
        },
    },
    plugins: [
        require("daisyui"),
        require('@tailwindcss/typography'),
    ],
    daisyui: {
        themes: [
            "light",
            "dark",
            "cupcake",
            "bumblebee",
            "emerald",
            "corporate",
            "synthwave",
            "retro",
            "cyberpunk",
            "valentine",
            "halloween",
            "garden",
            "forest",
            "aqua",
            "lofi",
            "pastel",
            "fantasy",
            "wireframe",
            "black",
            "luxury",
            "dracula",
            "cmyk",
            "autumn",
            "business",
            "acid",
            "lemonade",
            "night",
            "coffee",
            "winter",
            "dim",
            "nord",
            "sunset",
        ],
    },
};
